[package]
name = "image_json_build"
version = "0.1.0"
authors = ["SIPU <ddasik00@naver.com>"]
edition = "2018"

[dependencies]
image = "0.24.5"
lodepng = "3.7.2"
rgb = "0.8.35"
serde_json = "1.0.93"
serde_derive = "1.0.152"
serde = "1.0.152"
base64 = "0.21.0"

