[package]
name = "RS-json_build"
version = "0.1.0"
authors = ["SIPU <ddasik00@naver.com>"]
edition = "2018"

[dependencies]
image = "0.21.0"
lodepng = "2.4.2"
rgb = "0.8.13"
serde_json = "1.0.39"
serde_derive = "1.0.89"
serde = "1.0.89"
image-base64 = "0.1"