[package]
name = "image_json_build"
version = "0.1.0"
authors = ["SIPU <ddasik00@naver.com>"]
edition = "2018"

[dependencies]
image = "0.24.2"
lodepng = "3.7.0"
rgb = "0.8.33"
serde_json = "1.0.82"
serde_derive = "1.0.139"
serde = "1.0.139"
base64 = "0.13.0"
image-base64 = "0.1.0"
