[package]
name = "image_json_build"
version = "0.1.0"
authors = ["SIPU <ddasik00@naver.com>"]
edition = "2018"

[dependencies]
image = "0.24.6"
lodepng = "3.7.2"
rgb = "0.8.36"
serde_json = "1.0.96"
serde_derive = "1.0.164"
serde = "1.0.164"
base64 = "0.21.2"


